language: r
dist: trusty
sudo: required

# R version
r: bioc-devel

# Package caching only makes sense for the release versions.
#cache: packages

# Be strict when checking package
warnings_are_errors: true

# Package dependencies from CRAN not in DESCRIPTION file
r_binary_packages:
   - covr

# To send info to codecov
after_success:
  - Rscript -e 'library(covr);codecov()'
